import { defineConfig } from "orval";

/**
 * Generates the typed SimpleFit API client from the backend OpenAPI artifact.
 *
 * Input:  openapi/simplefit.api.json (verbatim snapshot of
 *         simplefit-api/openapi/simplefit.api.json, refreshed by `pnpm api:sync`)
 * Output: src/shared/api/generated/ (committed, DO NOT EDIT MANUALLY)
 *   model/      DTO types for every schema
 *   endpoints/  one folder per OpenAPI tag with plain request functions
 *               (usable from Server Components) and TanStack Query hooks
 *               (for Client Components)
 *
 * ORVAL_OUTPUT_DIR is used only by `pnpm api:check` to generate into a scratch
 * directory at the same depth for drift detection.
 */
const outputDir = process.env.ORVAL_OUTPUT_DIR ?? "src/shared/api/generated";

export default defineConfig({
  simplefit: {
    input: {
      target: "./openapi/simplefit.api.json",
    },
    output: {
      mode: "tags-split",
      target: `${outputDir}/endpoints`,
      schemas: `${outputDir}/model`,
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      override: {
        header: (info) => [
          "DO NOT EDIT MANUALLY.",
          "Generated by Orval from openapi/simplefit.api.json.",
          "Regenerate with `pnpm api:generate`; verify with `pnpm api:check`.",
          `${info.title ?? "API"} ${info.version ?? ""}`.trim(),
        ],
        mutator: {
          path: "./src/shared/api/http/api-fetch.ts",
          name: "apiFetch",
        },
        fetch: {
          // apiFetch resolves with the body and throws ApiError otherwise.
          includeHttpResponseReturnType: false,
        },
        query: {
          useQuery: true,
          useSuspenseQuery: false,
          useInfinite: false,
          signal: true,
        },
      },
    },
  },
});
