// Generated from docs/route-registry.json by scripts/generate-web-routes.mjs.
// Do not edit: change the registry (SF-31) and run `pnpm routes:generate`.

export const webRoutes = [
  {
    id: "web.account.appeal",
    path: "/account/appeal",
    params: [],
    shell: "web.account",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.account.pending-deletion",
    path: "/account/pending-deletion",
    params: [],
    shell: "web.account",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.account.suspended",
    path: "/account/suspended",
    params: [],
    shell: "web.account",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.admin",
    path: "/admin",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.access",
    path: "/admin/access",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.audit",
    path: "/admin/audit",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.campaigns",
    path: "/admin/campaigns",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.campaigns._campaign-id",
    path: "/admin/campaigns/:campaignId",
    params: ["campaignId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.campaigns",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.campaigns._campaign-id.edit",
    path: "/admin/campaigns/:campaignId/edit",
    params: ["campaignId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.campaigns._campaign-id",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.challenges.new",
    path: "/admin/challenges/new",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.enforcement",
    path: "/admin/enforcement",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.enterprise",
    path: "/admin/enterprise",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.enterprise._lead-id",
    path: "/admin/enterprise/:leadId",
    params: ["leadId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.enterprise",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.events._event-id",
    path: "/admin/events/:eventId",
    params: ["eventId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.flags",
    path: "/admin/flags",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.integrations",
    path: "/admin/integrations",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.login",
    path: "/admin/login",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: "web.admin",
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.admin.markets",
    path: "/admin/markets",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.moderation",
    path: "/admin/moderation",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.notifications",
    path: "/admin/notifications",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.notifications._template-id",
    path: "/admin/notifications/:templateId",
    params: ["templateId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.notifications",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.payouts",
    path: "/admin/payouts",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.pricing",
    path: "/admin/pricing",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.pricing._plan-id",
    path: "/admin/pricing/:planId",
    params: ["planId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.pricing",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.privacy",
    path: "/admin/privacy",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.promos",
    path: "/admin/promos",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.refunds",
    path: "/admin/refunds",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.revenue",
    path: "/admin/revenue",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.sponsors",
    path: "/admin/sponsors",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.sponsors._sponsor-id",
    path: "/admin/sponsors/:sponsorId",
    params: ["sponsorId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.sponsors",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.sponsors._sponsor-id.edit",
    path: "/admin/sponsors/:sponsorId/edit",
    params: ["sponsorId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.sponsors._sponsor-id",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.sponsors._sponsor-id.timeline",
    path: "/admin/sponsors/:sponsorId/timeline",
    params: ["sponsorId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.sponsors._sponsor-id",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.sponsors.revenue",
    path: "/admin/sponsors/revenue",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.sponsors",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.staff",
    path: "/admin/staff",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.subscriptions",
    path: "/admin/subscriptions",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.support",
    path: "/admin/support",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.support._session-id",
    path: "/admin/support/:sessionId",
    params: ["sessionId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.support",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.tenants",
    path: "/admin/tenants",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.tenants._tenant-id",
    path: "/admin/tenants/:tenantId",
    params: ["tenantId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.tenants",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.transactions",
    path: "/admin/transactions",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.users",
    path: "/admin/users",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.users._user-id",
    path: "/admin/users/:userId",
    params: ["userId"],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin.users",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ACTIVE",
  },
  {
    id: "web.admin.welcome",
    path: "/admin/welcome",
    params: [],
    shell: "web.admin",
    surface: "ADMIN",
    parent: "web.admin",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "ADMIN",
    phase: "ONBOARDING",
  },
  {
    id: "web.app",
    path: "/app",
    params: [],
    shell: "web.app",
    surface: "SYSTEM",
    parent: null,
    nav: "ENTRY",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.billing",
    path: "/app/billing",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.billing.downgrade",
    path: "/app/billing/downgrade",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app.billing",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.billing.invoices",
    path: "/app/billing/invoices",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app.billing",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.billing.invoices._invoice-id",
    path: "/app/billing/invoices/:invoiceId",
    params: ["invoiceId"],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app.billing.invoices",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.billing.upgrade",
    path: "/app/billing/upgrade",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app.billing",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.board",
    path: "/app/board",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.calendar",
    path: "/app/calendar",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.camp",
    path: "/app/camp",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "REDIRECT",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    redirectTo: "web.app.camp.board",
  },
  {
    id: "web.app.camp.board",
    path: "/app/camp/board",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app.camp",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.checkout",
    path: "/app/checkout",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.coach",
    path: "/app/coach",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.activity",
    path: "/app/coach/activity",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.board",
    path: "/app/coach/board",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.earnings",
    path: "/app/coach/earnings",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.earnings.transactions",
    path: "/app/coach/earnings/transactions",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach.earnings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.fighters",
    path: "/app/coach/fighters",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.fighters._fighter-id",
    path: "/app/coach/fighters/:fighterId",
    params: ["fighterId"],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach.fighters",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.payouts",
    path: "/app/coach/payouts",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.payouts.setup",
    path: "/app/coach/payouts/setup",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach.payouts",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.payouts.verify",
    path: "/app/coach/payouts/verify",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach.payouts",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.services.new",
    path: "/app/coach/services/new",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.sessions.new",
    path: "/app/coach/sessions/new",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.settings",
    path: "/app/coach/settings",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.coach.sparring.plan",
    path: "/app/coach/sparring/plan",
    params: [],
    shell: "web.app.coach",
    surface: "COACH",
    parent: "web.app.coach",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
  },
  {
    id: "web.app.community",
    path: "/app/community",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.discover",
    path: "/app/discover",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym",
    path: "/app/gym",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.announcements",
    path: "/app/gym/announcements",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.attendance",
    path: "/app/gym/attendance",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.board",
    path: "/app/gym/board",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.bookings",
    path: "/app/gym/bookings",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.challenges.new",
    path: "/app/gym/challenges/new",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.community",
    path: "/app/gym/community",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.leads",
    path: "/app/gym/leads",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.members",
    path: "/app/gym/members",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.members._member-id",
    path: "/app/gym/members/:memberId",
    params: ["memberId"],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.members",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.memberships",
    path: "/app/gym/memberships",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.memberships.new",
    path: "/app/gym/memberships/new",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.memberships",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.open-sparring",
    path: "/app/gym/open-sparring",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.open-sparring._open-sparring-id",
    path: "/app/gym/open-sparring/:openSparringId",
    params: ["openSparringId"],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.open-sparring",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.packages",
    path: "/app/gym/packages",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.payouts",
    path: "/app/gym/payouts",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.profile",
    path: "/app/gym/profile",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.promote",
    path: "/app/gym/promote",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.promote.results",
    path: "/app/gym/promote/results",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.promote",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.reports",
    path: "/app/gym/reports",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.revenue",
    path: "/app/gym/revenue",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.revenue.failed",
    path: "/app/gym/revenue/failed",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.revenue",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.revenue.transactions",
    path: "/app/gym/revenue/transactions",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.revenue",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings",
    path: "/app/gym/settings",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.community",
    path: "/app/gym/settings/community",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.danger",
    path: "/app/gym/settings/danger",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.integrations",
    path: "/app/gym/settings/integrations",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.locations",
    path: "/app/gym/settings/locations",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.plan",
    path: "/app/gym/settings/plan",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.settings.roles",
    path: "/app/gym/settings/roles",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym.settings",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.shared",
    path: "/app/gym/shared",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.staff",
    path: "/app/gym/staff",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.store",
    path: "/app/gym/store",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.gym.timetable",
    path: "/app/gym/timetable",
    params: [],
    shell: "web.app.gym",
    surface: "GYM",
    parent: "web.app.gym",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.app.home",
    path: "/app/home",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.marketplace",
    path: "/app/marketplace",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.messages",
    path: "/app/messages",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.onboarding.account",
    path: "/app/onboarding/account",
    params: [],
    shell: "web.app.onboarding",
    surface: "ONBOARDING",
    parent: "web.app",
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
  },
  {
    id: "web.app.onboarding.coach",
    path: "/app/onboarding/coach",
    params: [],
    shell: "web.app.onboarding",
    surface: "ONBOARDING",
    parent: "web.app",
    nav: "WIZARD",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
  },
  {
    id: "web.app.onboarding.fighter",
    path: "/app/onboarding/fighter",
    params: [],
    shell: "web.app.onboarding",
    surface: "ONBOARDING",
    parent: "web.app",
    nav: "WIZARD",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
  },
  {
    id: "web.app.onboarding.gym",
    path: "/app/onboarding/gym",
    params: [],
    shell: "web.app.onboarding",
    surface: "ONBOARDING",
    parent: "web.app",
    nav: "WIZARD",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
  },
  {
    id: "web.app.onboarding.role",
    path: "/app/onboarding/role",
    params: [],
    shell: "web.app.onboarding",
    surface: "ONBOARDING",
    parent: "web.app",
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
  },
  {
    id: "web.app.payments._payment-id",
    path: "/app/payments/:paymentId",
    params: ["paymentId"],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.profile",
    path: "/app/profile",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.progress",
    path: "/app/progress",
    params: [],
    shell: "web.app.fighter",
    surface: "FIGHTER",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
  },
  {
    id: "web.app.settings.data",
    path: "/app/settings/data",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.app.settings.security",
    path: "/app/settings/security",
    params: [],
    shell: "web.app.active",
    surface: "SHARED",
    parent: "web.app",
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
  },
  {
    id: "web.coaches",
    path: "/coaches",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.dev.design-system",
    path: "/dev/design-system",
    params: [],
    shell: "web.root",
    surface: "INTERNAL",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.fighters",
    path: "/fighters",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.gyms",
    path: "/gyms",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.login",
    path: "/login",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: null,
    nav: "WIZARD",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.login.code",
    path: "/login/code",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: "web.login",
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.marketplace",
    path: "/marketplace",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.not-found",
    path: "/*",
    params: [],
    shell: "web.root",
    surface: "SYSTEM",
    parent: null,
    nav: "CATCH_ALL",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.partners",
    path: "/partners",
    params: [],
    shell: "web.site",
    surface: "ONBOARDING",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.partners.apply",
    path: "/partners/apply",
    params: [],
    shell: "web.site",
    surface: "ONBOARDING",
    parent: "web.partners",
    nav: "WIZARD",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.pricing",
    path: "/pricing",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.pricing.compare",
    path: "/pricing/compare",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: "web.pricing",
    nav: "STACK",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.root",
    path: "/",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.signup",
    path: "/signup",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.signup.account",
    path: "/signup/account",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: "web.signup",
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.signup.verify",
    path: "/signup/verify",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: "web.signup",
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.sponsor.analytics._campaign-id",
    path: "/sponsor/analytics/:campaignId",
    params: ["campaignId"],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "STANDALONE",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.application",
    path: "/sponsor/application",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ONBOARDING",
  },
  {
    id: "web.sponsor.campaigns",
    path: "/sponsor/campaigns",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.campaigns._campaign-id",
    path: "/sponsor/campaigns/:campaignId",
    params: ["campaignId"],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: "web.sponsor.campaigns",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.campaigns.new",
    path: "/sponsor/campaigns/new",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: "web.sponsor.campaigns",
    nav: "STACK",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.dashboard",
    path: "/sponsor/dashboard",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.invoices",
    path: "/sponsor/invoices",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.sponsor.login",
    path: "/sponsor/login",
    params: [],
    shell: "web.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
  },
  {
    id: "web.sponsor.settings",
    path: "/sponsor/settings",
    params: [],
    shell: "web.sponsor",
    surface: "SPONSOR",
    parent: null,
    nav: "NAV_ITEM",
    session: "AUTHENTICATED",
    capability: "SPONSOR_WORKSPACE",
    phase: "ACTIVE",
  },
  {
    id: "web.verify-email",
    path: "/verify-email",
    params: [],
    shell: "web.minimal",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
  {
    id: "web.white-label",
    path: "/white-label",
    params: [],
    shell: "web.site",
    surface: "SITE",
    parent: null,
    nav: "STANDALONE",
    session: "PUBLIC",
    capability: null,
    phase: null,
  },
] as const;

export const webShells = [
  {
    id: "web.root",
    parent: null,
    navItems: [],
  },
  {
    id: "web.site",
    parent: "web.root",
    navItems: [],
  },
  {
    id: "web.auth",
    parent: "web.root",
    navItems: [],
  },
  {
    id: "web.minimal",
    parent: "web.root",
    navItems: [],
  },
  {
    id: "web.account",
    parent: "web.root",
    navItems: [],
  },
  {
    id: "web.app",
    parent: "web.root",
    navItems: [],
  },
  {
    id: "web.app.onboarding",
    parent: "web.app",
    navItems: [],
  },
  {
    id: "web.app.fighter",
    parent: "web.app",
    navItems: [
      {
        key: "home",
        route: "web.app.home",
      },
      {
        key: "board",
        route: "web.app.board",
      },
      {
        key: "training",
        route: "web.app.camp.board",
      },
      {
        key: "progress",
        route: "web.app.progress",
      },
      {
        key: "community",
        route: "web.app.community",
      },
      {
        key: "discover",
        route: "web.app.discover",
      },
      {
        key: "profile",
        route: "web.app.profile",
      },
      {
        key: "market",
        route: "web.app.marketplace",
      },
      {
        key: "calendar",
        route: "web.app.calendar",
      },
      {
        key: "messages",
        route: "web.app.messages",
      },
      {
        key: "settings",
        route: "web.app.settings.security",
      },
    ],
  },
  {
    id: "web.app.coach",
    parent: "web.app",
    navItems: [
      {
        key: "dashboard",
        route: "web.app.coach",
      },
      {
        key: "activity",
        route: "web.app.coach.activity",
      },
      {
        key: "fighters",
        route: "web.app.coach.fighters",
      },
      {
        key: "board",
        route: "web.app.coach.board",
      },
      {
        key: "programs",
        route: "web.app.coach.sessions.new",
      },
      {
        key: "sparring",
        route: "web.app.coach.sparring.plan",
      },
      {
        key: "calendar",
        route: "web.app.calendar",
      },
      {
        key: "services",
        route: "web.app.coach.services.new",
      },
      {
        key: "earnings",
        route: "web.app.coach.earnings",
      },
      {
        key: "billing",
        route: "web.app.billing",
      },
      {
        key: "messages",
        route: "web.app.messages",
      },
      {
        key: "settings",
        route: "web.app.coach.settings",
      },
    ],
  },
  {
    id: "web.app.gym",
    parent: "web.app",
    navItems: [
      {
        key: "dashboard",
        route: "web.app.gym",
      },
      {
        key: "board",
        route: "web.app.gym.board",
      },
      {
        key: "reports",
        route: "web.app.gym.reports",
      },
      {
        key: "members",
        route: "web.app.gym.members",
      },
      {
        key: "leads",
        route: "web.app.gym.leads",
      },
      {
        key: "staff",
        route: "web.app.gym.staff",
      },
      {
        key: "timetable",
        route: "web.app.gym.timetable",
      },
      {
        key: "bookings",
        route: "web.app.gym.bookings",
      },
      {
        key: "attendance",
        route: "web.app.gym.attendance",
      },
      {
        key: "shared",
        route: "web.app.gym.shared",
      },
      {
        key: "community",
        route: "web.app.gym.community",
      },
      {
        key: "challenges",
        route: "web.app.gym.challenges.new",
      },
      {
        key: "sparring",
        route: "web.app.gym.open-sparring",
      },
      {
        key: "announcements",
        route: "web.app.gym.announcements",
      },
      {
        key: "memberships",
        route: "web.app.gym.memberships",
      },
      {
        key: "revenue",
        route: "web.app.gym.revenue",
      },
      {
        key: "store",
        route: "web.app.gym.store",
      },
      {
        key: "promote",
        route: "web.app.gym.promote",
      },
      {
        key: "branding",
        route: "web.app.gym.profile",
      },
      {
        key: "settings",
        route: "web.app.gym.settings",
      },
    ],
  },
  {
    id: "web.app.active",
    parent: "web.app",
    navItems: [],
  },
  {
    id: "web.sponsor",
    parent: "web.root",
    navItems: [
      {
        key: "overview",
        route: "web.sponsor.dashboard",
      },
      {
        key: "applications",
        route: "web.sponsor.application",
      },
      {
        key: "campaigns",
        route: "web.sponsor.campaigns",
      },
      {
        key: "challenges",
        route: "web.sponsor.campaigns",
        query: {
          type: "challenge",
        },
      },
      {
        key: "events",
        route: "web.sponsor.campaigns",
        query: {
          type: "event",
        },
      },
      {
        key: "creative",
        route: null,
      },
      {
        key: "analytics",
        route: null,
      },
      {
        key: "invoices",
        route: "web.sponsor.invoices",
      },
      {
        key: "settings",
        route: "web.sponsor.settings",
      },
    ],
  },
  {
    id: "web.admin",
    parent: "web.root",
    navItems: [
      {
        key: "overview",
        route: "web.admin",
      },
      {
        key: "tenants",
        route: "web.admin.tenants",
      },
      {
        key: "users",
        route: "web.admin.users",
      },
      {
        key: "revenue",
        route: "web.admin.revenue",
      },
      {
        key: "subscriptions",
        route: "web.admin.subscriptions",
      },
      {
        key: "transactions",
        route: "web.admin.transactions",
      },
      {
        key: "payments",
        route: "web.admin.payouts",
      },
      {
        key: "pricing",
        route: "web.admin.pricing",
      },
      {
        key: "sponsors",
        route: "web.admin.sponsors",
      },
      {
        key: "campaigns",
        route: "web.admin.campaigns",
      },
      {
        key: "enterprise",
        route: "web.admin.enterprise",
      },
      {
        key: "moderation",
        route: "web.admin.moderation",
      },
      {
        key: "enforcement",
        route: "web.admin.enforcement",
      },
      {
        key: "support",
        route: "web.admin.support",
      },
      {
        key: "privacy",
        route: "web.admin.privacy",
      },
      {
        key: "audit",
        route: "web.admin.audit",
      },
      {
        key: "flags",
        route: "web.admin.flags",
      },
      {
        key: "notifications",
        route: "web.admin.notifications",
      },
      {
        key: "integrations",
        route: "web.admin.integrations",
      },
      {
        key: "markets",
        route: "web.admin.markets",
      },
      {
        key: "staff",
        route: "web.admin.staff",
      },
    ],
  },
] as const;

export const webGuards = {
  signIn: {
    web: "web.login",
    "web.sponsor": "web.sponsor.login",
    "web.admin": "web.admin.login",
  },
  entry: "web.app",
  notFound: "web.not-found",
  restrictedAccount: {
    suspended: "web.account.suspended",
    pendingDeletion: "web.account.pending-deletion",
  },
  returnToParam: "returnTo",
  intentParam: "intent",
  accountOnboarding: ["web.app.onboarding.account", "web.app.onboarding.role"],
  entryDestinations: {
    account_registration: "web.app.onboarding.account",
    role_selection: "web.app.onboarding.role",
    fighter_onboarding: "web.app.onboarding.fighter",
    fighter_home: "web.app.home",
    coach_onboarding: "web.app.onboarding.coach",
    gym_onboarding: "web.app.onboarding.gym",
    sponsor_application: "web.partners.apply",
  },
} as const;
